# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
  
pool:
  name: Service

steps:
- checkout: self
  persistCredentials: true
  clean: true
  displayName: 'Allow Scripts to Access System Token'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script:
    npm install
  displayName: 'Install Dependencies'

- script:
    npm run test
  displayName: 'Run Unit Tests'

- script:
    npm run package_win
  displayName: 'Transpile Component'

- script:
    npm run update_version
  displayName: 'Update Component Version'

- task: BatchScript@1
  inputs:
    filename: 'merge.bat'
  displayName: 'Merge Changes Back to Master Branch'

- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: 'react-components'
  displayName: 'Publish NPM module'